ExpenseTracker.Website/Controllers/CheckVouchersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataApp.Core.DAL;
using DataApp.Core.Models;
using DataApp.Core;

namespace ExpenseTracker.Website.Controllers
{
    public class CheckVouchersController : Controller
    {
        private DataAppFacade db = new DataAppFacade();
        private List<TransactionAccount> transactionAccounts = new List<TransactionAccount>();

        public CheckVouchersController()
        {
            this.transactionAccounts = db.TransactionAccountController.GetAll();
        }

        // GET: CheckVouchers
        public async Task<ActionResult> Index()
        {
            ViewBag.TransactionAccounts = this.transactionAccounts;
            if (Request["search"] != null)
            {
                string query = (string)Request["search"].ToLower();
                //return View(await db.CheckVouchers.Where(p => p.Notes.ToLower().Contains(query)).ToListAsync());
                return View(db.CheckVoucherController.Find(query));
            }

            //return View(await db.CheckVouchers.ToListAsync());
            return View( db.CheckVoucherController.GetAll());
        }

        // GET: CheckVouchers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckVoucher checkVoucher = db.CheckVoucherController.Get(c => c.Id == id); //await db.CheckVouchers.FindAsync(id);
            if (checkVoucher == null)
            {
                return HttpNotFound();
            }
            return View(checkVoucher);
        }

        // GET: CheckVouchers/Create
        public ActionResult Create()
        {
            ViewBag.PayeeId = new SelectList(this.transactionAccounts, "Id", "Name");
            return View();
        }

        // POST: CheckVouchers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Amount,DueDate,EntryDate,CheckNo,VoucherNo,Notes,PayeeId")] CheckVoucher checkVoucher)
        {
            if (ModelState.IsValid)
            {
                db.CheckVoucherController.Add(checkVoucher);
                //await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PayeeId = new SelectList(this.transactionAccounts, "Id", "Name", checkVoucher.PayeeId);
            return View(checkVoucher);
        }

        // GET: CheckVouchers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckVoucher checkVoucher = this.db.CheckVoucherController.Get(c => c.Id == id); //await db.CheckVouchers.FindAsync(id);
            if (checkVoucher == null)
            {
                return HttpNotFound();
            }
            ViewBag.PayeeId = new SelectList(this.transactionAccounts, "Id", "Name", checkVoucher.PayeeId);
            return View(checkVoucher);
        }

        // POST: CheckVouchers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Amount,DueDate,EntryDate,CheckNo,VoucherNo,Notes,PayeeId")] CheckVoucher checkVoucher)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(checkVoucher).State = EntityState.Modified;
                //await db.SaveChangesAsync();
                db.CheckVoucherController.Update(checkVoucher);
                return RedirectToAction("Index");
            }
            ViewBag.PayeeId = new SelectList(this.transactionAccounts, "Id", "Name", checkVoucher.PayeeId);

            return View(checkVoucher);
        }

        // GET: CheckVouchers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckVoucher checkVoucher = this.db.CheckVoucherController.Get(c => c.Id == id); //await db.CheckVouchers.FindAsync(id);
            if (checkVoucher == null)
            {
                return HttpNotFound();
            }
            return View(checkVoucher);
        }

        // POST: CheckVouchers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            //CheckVoucher checkVoucher = await db.CheckVouchers.FindAsync(id);
            //db.CheckVouchers.Remove(checkVoucher);
            //await db.SaveChangesAsync();
            this.db.CheckVoucherController.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpenseTracker.Website/Controllers/TransactionAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataApp.Core.DAL;
using DataApp.Core.Models;
using DataApp.Core;

namespace ExpenseTracker.Website.Controllers
{
    [Authorize]
    public class TransactionAccountsController : Controller
    {
        private DataAppFacade db = new DataAppFacade();

        // GET: TransactionAccounts
        public async Task<ActionResult> Index()
        {
            //return View(await db.TransactionAccounts.ToListAsync());
            return View(db.TransactionAccountController.GetAll());
        }

        // GET: TransactionAccounts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionAccount transactionAccount = db.TransactionAccountController.Get(id); //await db.TransactionAccounts.FindAsync(id);
            if (transactionAccount == null)
            {
                return HttpNotFound();
            }
            return View(transactionAccount);
        }

        // GET: TransactionAccounts/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Notes")] TransactionAccount transactionAccount)
        {
            if (ModelState.IsValid)
            {
                //db.TransactionAccounts.Add(transactionAccount);
                //await db.SaveChangesAsync();
                db.TransactionAccountController.Add(transactionAccount);
                return RedirectToAction("Index");
            }

            return View(transactionAccount);
        }

        // GET: TransactionAccounts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionAccount transactionAccount = db.TransactionAccountController.Get(id); //await db.TransactionAccounts.FindAsync(id);
            if (transactionAccount == null)
            {
                return HttpNotFound();
            }
            return View(transactionAccount);
        }

        // POST: TransactionAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Notes")] TransactionAccount transactionAccount)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(transactionAccount).State = EntityState.Modified;
                //await db.SaveChangesAsync();
                this.db.TransactionAccountController.Update(transactionAccount);
                return RedirectToAction("Index");
            }
            return View(transactionAccount);
        }

        // GET: TransactionAccounts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransactionAccount transactionAccount = this.db.TransactionAccountController.Get(id); //await db.TransactionAccounts.FindAsync(id);
            if (transactionAccount == null)
            {
                return HttpNotFound();
            }
            return View(transactionAccount);
        }

        // POST: TransactionAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            //TransactionAccount transactionAccount = await db.TransactionAccounts.FindAsync(id);
            //db.TransactionAccounts.Remove(transactionAccount);
            //await db.SaveChangesAsync();
            this.db.TransactionAccountController.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpenseTracker.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Expense Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("style", required: false)
    <style>
        .inline-block {
            display: inline-block;
        }
    </style>

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Expense Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Manage Records <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Check Vouchers", "Index", "CheckVouchers")</li>
                                <li>@Html.ActionLink("Expenses", "Index", "Expenses")</li>
                                <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
                                <li>@Html.ActionLink("Transaction Accounts", "Index", "TransactionAccounts")</li>
                                @*<li class="divider"></li>
                                <li class="dropdown-header">---</li>
                                <li>@Html.ActionLink("Expense Items", "Index", "ExpenseItems")</li>
                                <li>@Html.ActionLink("Check Transactions", "Index", "CheckTransactions")</li>*@
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)">Reports</a></li>
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Expense Tracker</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>